### PR TITLE
:arrow_double_up: Stop sharing volumes in test

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
This is a branch from #2 as an experiment to see if it resolves build issues.

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
@neilbmclaughlin what build issues?

**Comment by neilbmclaughlin** [comment]
@st3v3nhunt - could you review and if OK merge these changes into your PR so we get these changes and also preserve the discussion in your PR.

The details of the changes are in the individual commits.

**Comment by neilbmclaughlin** [comment]
@st3v3nhunt - needs further investigation

**Comment by neilbmclaughlin** [comment]
No longer required

**Pull request closed without merging**
