### PR TITLE
Remove Splunk HEC variables

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by adamgraves-choices** [comment]
Still need `nearby-services-api` to log to stdout.

**Comment by beseven** [comment]
@adamgraves-choices, I'll look at `nearby-services-api` in the morning then

**Comment by st3v3nhunt** [comment]
@adamgraves-choices I don't think these changes need new versions. It isn't a big enough change IMO

**Comment by adamgraves-choices** [comment]
@st3v3nhunt Updated as discussed this morning.

**Review by neilbmclaughlin — APPROVED** [review]

**Pull request merged**
